# from https://github.com/chimera-suite/use-case/blob/master/docker-compose-jena-fuseki.yml
version: "3"
services:
  jena-fuseki:
    hostname: jena-fuseki
    container_name: jena-fuseki
    image: stain/jena-fuseki
    environment:
       - "ADMIN_PASSWORD=admin"
       - "QUERY_TIMEOUT=500000"
    ports:
        - "3030:3030"
    volumes:
      # Overwrite FUSEKI_HOME/shiro.ini for use by entrypoint
      - "./shiro.ini:/jena-fuseki/shiro.ini"

  apacheds:
    hostname: apacheds
    container_name: apacheds
    image: openmicroscopy/apacheds
    ports:
        - "10389:10389"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:10389"]
        interval: 30s
        timeout: 10s
        retries: 5

  setup:
    image: openmicroscopy/apacheds
    volumes: ["./setup.sh:/setup.sh"]
    entrypoint: "bash"
    command: "/setup.sh"
    restart: "no"
    environment:
       - "LDAP_HOST=apacheds"
       - "QUERY_TIMEOUT=500000"
    depends_on:
      - apacheds
